################################# Default configuration ###################
baseURL = "https://eurodesignstonellc.com"
title = "Euro Design Stone"
theme = ["meghna-hugo", "hugo-shortcode-gallery"]
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"]

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "https://www.google.com/recaptcha/api.js"

################### English Navigation ########################

[[Languages.en.menu.main]]
name = "GALLERY"
url = "#blog"
weight = 3

[[Languages.en.menu.main]]
name = "SERVICES"
url = "#services"
weight = 2


[[Languages.en.menu.main]]
name = "CONTACT 253-886-0784"
url = "#contact"
weight = 4


[[Languages.en.menu.main]]
name = "HOME"
url = "#banner"
weight = 1




############################# Default Parameters ##########################
[params]
logo = ""
# Meta data
description = "Professional tile installation in the Greater Seattle area"
#author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = false
preloader = ""

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "47.080753"
map_longitude = "-122.408290"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "facebook.com"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2022 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
attribution = "<a href='https://www.flaticon.com/free-icons/user' title='user icons'>User icons created by Smashicons - Flaticon</a>"

################################ France Language ########################